const runner_cards = {
    'Early Worm' : 'program',
    'Matador' : 'program',
    'MS-todon' : 'program',
    'Psychic Friend' : 'program',
    'Rent-I-Con' : 'program',
    'Schematics Search Engine' : 'program',
    'Superglue' : 'program',
    'Armageddon' : 'program',
    'Big Frackin\' Gun' : 'program',
    'Black Widow' : 'program',
    'Boring Bit' : 'program',
    'Bulldozer' : 'program',
    'Corrosion' : 'program',
    'Crumble' : 'program',
    'Disintegrator' : 'program',
    'Enterprise, Inc., Shields' : 'program',
    'Forward\'s Legacy' : 'program',
    'Fubar' : 'program',
    'Garbage In' : 'program',
    'Highlighter' : 'program',
    'Lockjaw' : 'program',
    'Morphing Tool' : 'program',
    'Redecorator' : 'program',
    'Scaldan' : 'program',
    'Skeleton Passkeys' : 'program',
    'Skullcap' : 'program',
    'Taxman' : 'program',
    'Vienna 22' : 'program',
    'Viral Pipeline' : 'program',
    'Wrecking Ball' : 'program',
    'Loony Goon' : 'program',
    'Piledriver' : 'program',
    'Raffles' : 'program',
    'Ramming Piston' : 'program',
    'Raptor' : 'program',
    'Shaka' : 'program',
    'Tinweasel' : 'program',
    'Wild Card' : 'program',
    'Wizard\'s Book' : 'program',
    'Worm' : 'program',
    'Black Dahlia' : 'program',
    'Codecracker' : 'program',
    'Codeslinger' : 'program',
    'Cyfermaster' : 'program',
    'Hammer' : 'program',
    'Jackhammer' : 'program',
    'Afreet' : 'program',
    'Bakdoor' : 'program',
    'Blink' : 'program',
    'Boardwalk' : 'program',
    'Butcher Boy' : 'program',
    'Cascade' : 'program',
    'Cockroach' : 'program',
    'Dogcatcher' : 'program',
    'Dropp' : 'program',
    'Expert Schedule Analyzer' : 'program',
    'Fait Accompli' : 'program',
    'Flak' : 'program',
    'Gremlins' : 'program',
    'Grubb' : 'program',
    'I Spy' : 'program',
    'Imp' : 'program',
    'Krash' : 'program',
    'Mouse' : 'program',
    'Newsgroup Filter' : 'program',
    'Pattel\'s Virus' : 'program',
    'Pox' : 'program',
    'R&D Protocol File' : 'program',
    'Rabbit' : 'program',
    'Replicator' : 'program',
    'Shredder Uplink Protocol' : 'program',
    'Signpost' : 'program',
    'Skivviss' : 'program',
    'Speed Trap' : 'program',
    'Startup Immolator' : 'program',
    'Zetatech Software Installer' : 'program',
    'Baedeker\'s Net Map' : 'program',
    'Cloak' : 'program',
    'Invisibility' : 'program',
    'SeeYa' : 'program',
    'Shield' : 'program',
    'Smarteye' : 'program',
    'Vewy Vewy Quiet' : 'program',
    'Force Shield' : 'program',
    'Dwarf' : 'program',
    'Clown' : 'program',
    'Microtech AI Interface' : 'program',
    'Mystery Box' : 'program',
    'Netspace Inverter' : 'program',
    'Reflector' : 'program',
    'Scatter Shot' : 'program',
    'Self-Modifying Code' : 'program',
    'Snowball' : 'program',
    'Succubus' : 'program',
    'AI Boon' : 'program',
    'Bartmoss Memorial Icebreaker' : 'program',
    'Dupre' : 'program',
    'Emergency Self-Construct' : 'program',
    'Evil Twin' : 'program',
    'False Echo' : 'program',
    'Incubator' : 'program',
    'Japanese Water Torture' : 'program',
    'Joan of Arc' : 'program',
    'Poltergeist' : 'program',
    'Deep Thought' : 'program',
    'Record Reconstructor' : 'hardware',
    'Little Black Box' : 'hardware',
    'Omnitech "Spinal Tap" Cybermodem' : 'hardware',
    'Omnitech Wet Drive' : 'hardware',
    'Vintage Camaro' : 'hardware',
    'Zetatech Portastation' : 'hardware',
    'Crash Space' : 'hardware',
    'Elena Laskova' : 'hardware',
    'Executive File Clerk' : 'hardware',
    'Sandbox Dig' : 'hardware',
    'Cortical Cybermodem' : 'hardware',
    'Cortical Stimulators' : 'hardware',
    'Eurocorpse(tm) Spin Chip' : 'hardware',
    'Lucidrine(tm) Drip Feed' : 'hardware',
    'Sunburst Cranial Interface' : 'hardware',
    'The Deck' : 'hardware',
    'Nasuko Cycle' : 'hardware',
    'Raven Microcyb Owl' : 'hardware',
    'Techtronica Utility Suit' : 'hardware',
    '"Armadillo" Armored Road Home' : 'hardware',
    'Armored Fridge' : 'hardware',
    'Artemis 2020' : 'hardware',
    'Dermatech Bodyplating' : 'hardware',
    '"Drifter" Mobile Environment' : 'hardware',
    'Militech MRAM Chip' : 'hardware',
    'MRAM Chip' : 'hardware',
    'Pandora\'s Deck' : 'hardware',
    'Parraline 5750' : 'hardware',
    'PK-6089a' : 'hardware',
    'R&D Interface' : 'hardware',
    'Raven Microcyb Eagle' : 'hardware',
    'Tycho Mem Chip' : 'hardware',
    'WuTech Mem Chip' : 'hardware',
    'Zetatech Mem Chip' : 'hardware',
    'ZZ22 Speed Chip' : 'hardware',
    'Corolla Speed Chip' : 'hardware',
    '"Green Knight" Surge Buffers' : 'hardware',
    'HQ Interface' : 'hardware',
    'Microtech Backup Drive' : 'hardware',
    'Lifesaver Nanosurgeons' : 'hardware',
    'Microtech \'Trode Set' : 'hardware',
    'Full Body Conversion' : 'hardware',
    'Bodyweight(tm) Data Creche' : 'hardware',
    'Arasaka Portable Prototype' : 'hardware',
    'Crash Space' : 'resource',
    'Elena Laskova' : 'resource',
    'Executive File Clerk' : 'resource',
    'Sandbox Dig' : 'resource',
    'Airport Locker' : 'resource',
    'Back Door to Netwatch' : 'resource',
    'Back Door to Rivals' : 'resource',
    'Bargain with Viacox' : 'resource',
    'Bolt-Hole' : 'resource',
    'Chiba Bank Account' : 'resource',
    'Credit Subversion' : 'resource',
    'Death from Above' : 'resource',
    'Expendable Family Member' : 'resource',
    'Get Ready to Rumble' : 'resource',
    'HQ Mole' : 'resource',
    'Liberated Savings Account' : 'resource',
    'Mercenary Subcontract' : 'resource',
    'Precision Bribery' : 'resource',
    'R&D Mole' : 'resource',
    'Runner Sensei' : 'resource',
    'Simulacrum' : 'resource',
    'Streetware Distributor' : 'resource',
    'Swiss Bank Account' : 'resource',
    'Time to Collect' : 'resource',
    'Wired Switchboard' : 'resource',
    'Access to Arasaka' : 'resource',
    'Access to Kiribati' : 'resource',
    'Back Door to Orbital Air' : 'resource',
    'Fall Guy' : 'resource',
    'Nomad Allies' : 'resource',
    'Danshi\'s Second ID' : 'resource',
    'Databroker' : 'resource',
    'Floating Runner BBS' : 'resource',
    'Hell\'s Run' : 'resource',
    'Junkyard BBS' : 'resource',
    'Karl de Veres, Corporate Stooge' : 'resource',
    'Loan from Chiba' : 'resource',
    'Restrictive Net Zoning' : 'resource',
    'Smith\'s Pawnshop' : 'resource',
    'Submarine Uplink' : 'resource',
    'Technician Lover' : 'resource',
    'Trauma Team' : 'resource',
    'Umbrella Policy' : 'resource',
    'Wilson, Weeflerunner Apprentice' : 'resource',
    'Back Door to Hilliard' : 'resource',
    'Broker' : 'resource',
    'Crash Everett, Inventive Fixer' : 'resource',
    'Leland, Corporate Bodyguard' : 'resource',
    'Rigged Investments' : 'resource',
    'The Short Circuit' : 'resource',
    'Short-Term Contract' : 'resource',
    'The Springboard' : 'resource',
    'Access Through Alpha' : 'resource',
    'Aujourd\'Oui' : 'resource',
    'Code Viral Cache' : 'resource',
    'Corporate Ally' : 'resource',
    'Diplomatic Immunity' : 'resource',
    'N.E.T.O.' : 'resource',
    'Preying Mantis' : 'resource',
    'Ronin Around' : 'resource',
    'The Shell Traders' : 'resource',
    'Silicon Saloon Franchise' : 'resource',
    'Top Runners Conference' : 'resource',
    'Quest for Cattekin' : 'resource',
    'Field Reporter for Ice and Data' : 'resource',
    'Anonymous Tip' : 'event',
    'Arasaka Owns You' : 'event',
    'Deal with Militech' : 'event',
    'Desperate Competitor' : 'event',
    'Forged Activation Orders' : 'event',
    'Fortress Respecification' : 'event',
    'misc.for-sale' : 'event',
    'MIT West Tier' : 'event',
    'Organ Donor' : 'event',
    'Playful AI' : 'event',
    'Sneak Preview' : 'event',
    'Stumble through Wilderspace' : 'event',
    'Synchronized Attack on HQ' : 'event',
    'Terrorist Reprisal' : 'event',
    'Total Genetic Retrofit' : 'event',
    'Priority Wreck' : 'event',
    'Hot Tip for WNS' : 'event',
    'Bodyweight Synthetic Blood' : 'event',
    'Core Command: Jettison Ice' : 'event',
    'Inside Job' : 'event',
    'Kilroy Was Here' : 'event',
    'Lucidrine Booster Drug' : 'event',
    'Private LDL Access' : 'event',
    'Romp through HQ' : 'event',
    'Security Code WORM Chip' : 'event',
    'Social Engineering' : 'event',
    'Valu-Pak Software Bundle' : 'event',
    'Weather-to-Finance Pipe' : 'event',
    'Ice and Data\'s Guide to the Net' : 'event',
    'All-Nighter' : 'event',
    'Custodial Position' : 'event',
    'Edited Shipping Manifests' : 'event',
    'Executive Wiretaps' : 'event',
    'Forgotten Backup Chip' : 'event',
    'Gideon\'s Pawn Shop' : 'event',
    'Hunt Club BBS' : 'event',
    'If You Want It Done Right...' : 'event',
    'Jack \'n\' Joe' : 'event',
    'Livewire\'s Contacts' : 'event',
    'Mantis, Fixer-at-Large' : 'event',
    'Open-Ended Mileage Program' : 'event',
    'Score!' : 'event',
    'Temple Microcode Outlet' : 'event',
    'All-Hands' : 'event',
    'Blackmail' : 'event',
    'Cruising for Netwatch' : 'event',
    'Decoy Signal' : 'event',
    'Demolition Run' : 'event',
    'Disgruntled Ice Technician' : 'event',
    'Drone for a Day' : 'event',
    'Faked Hit' : 'event',
    'Frame-Up' : 'event',
    'Hijack' : 'event',
    'Ice and Data Special Report' : 'event',
    'Identity Donor' : 'event',
    'Live News Feed' : 'event',
    'On the Fast Track' : 'event',
    'Pirate Broadcast' : 'event',
    'Poisoned Water Supply' : 'event',
    'Prearranged Drop' : 'event',
    'Promises, Promises' : 'event',
    'Reconnaissance' : 'event',
    'Remote Detonator' : 'event',
    'Rush Hour' : 'event',
    'Senatorial Field Trip' : 'event',
    'Stakeout' : 'event',
    'Subliminal Corruption' : 'event',
    'Test Spin' : 'event',
    'The Personal Touch' : 'event',
    'Weefle Initiation' : 'event',
    'Boostergang Connections' : 'event',
    'Corruption' : 'event',
    'Do the \'Drine [TM]' : 'event',
    'Finders Keepers' : 'event',
    'Gypsy [TM] Schedule Analyzer' : 'event',
    'Library Search' : 'event',
    'Meat Upgrade' : 'event',
    'Networking' : 'event',
    'Panzer Run' : 'event',
    'Running Interference' : 'event',
}

const corp_cards = {
    'Baskerville' : 'ice',
    'Bolter Swarm' : 'ice',
    'Brain Drain' : 'ice',
    'Deadeye' : 'ice',
    'Dumpster' : 'ice',
    'Entrapment' : 'ice',
    'Glacier' : 'ice',
    'Imperial Guard' : 'ice',
    'Puzzle' : 'ice',
    'Trapdoor' : 'ice',
    'Vortex' : 'ice',
    'Brain Wash' : 'ice',
    'Bug Zapper' : 'ice',
    'Caryatid' : 'ice',
    'Chihuahua' : 'ice',
    'Colonel Failure' : 'ice',
    'Coyote' : 'ice',
    'Credit Blocks' : 'ice',
    'Datacomb' : 'ice',
    'Death Yo-Yo' : 'ice',
    'Digiconda' : 'ice',
    'Dog Pile' : 'ice',
    'Food Fight' : 'ice',
    'Galatea' : 'ice',
    'Gatekeeper' : 'ice',
    'Homing Missile' : 'ice',
    'Hunting Pack' : 'ice',
    'Iceberg' : 'ice',
    'Lesser Arcana' : 'ice',
    'Marionette' : 'ice',
    'Mastermind' : 'ice',
    'Minotaur' : 'ice',
    'Misleading Access Menus' : 'ice',
    'Mobile Barricade' : 'ice',
    'Riddler' : 'ice',
    'Roadblock' : 'ice',
    'Sandstorm' : 'ice',
    'Scaffolding' : 'ice',
    'Snowbank' : 'ice',
    'Sphinx 2006' : 'ice',
    'Sumo 2008' : 'ice',
    'Toughonium(tm) Wall' : 'ice',
    'Tumblers' : 'ice',
    'Twisty Passages' : 'ice',
    'Walking Wall' : 'ice',
    'Washed-Up Solo Construct' : 'ice',
    'Cortical Scanner' : 'ice',
    'Endless Corridor' : 'ice',
    'Fatal Attractor' : 'ice',
    'Wall of Ice' : 'ice',
    'Tutor' : 'ice',
    'Vacuum Link' : 'ice',
    'Laser Wire' : 'ice',
    'Razor Wire' : 'ice',
    'Reinforced Wall' : 'ice',
    'Too Many Doors' : 'ice',
    'Shotgun Wire' : 'ice',
    'Nerve Labyrinth' : 'ice',
    'Haunting Inquisition' : 'ice',
    'Ball and Chain' : 'ice',
    'Canis Major' : 'ice',
    'Canis Minor' : 'ice',
    'Cinderella' : 'ice',
    'Code Corpse' : 'ice',
    'Data Darts' : 'ice',
    'Data Naga' : 'ice',
    'Data Raven' : 'ice',
    'Fragmentation Storm' : 'ice',
    'Hunter' : 'ice',
    'Jack Attack' : 'ice',
    'Liche' : 'ice',
    'Mastiff' : 'ice',
    'Mazer' : 'ice',
    'Pocket Virtual Reality' : 'ice',
    'Rock is Strong' : 'ice',
    'Sentinels Prime' : 'ice',
    'Shock.r' : 'ice',
    'Viral 15' : 'ice',
    'Virizz' : 'ice',
    'PI in the \'Face' : 'ice',
    'Asp' : 'ice',
    'Homewrecker' : 'ice',
    'Ice Pick Willie' : 'ice',
    'Keeper' : 'ice',
    'Neural Blade' : 'ice',
    'Quandary' : 'ice',
    'Rex' : 'ice',
    'Scramble' : 'ice',
    'Sleeper' : 'ice',
    'TKO 2.0' : 'ice',
    'Triggerman' : 'ice',
    'Wall of Static' : 'ice',
    'Zombie' : 'ice',
    'Cortical Scrub' : 'ice',
    'Crystal Wall' : 'ice',
    'D\'Arc Knight' : 'ice',
    'Data Wall' : 'ice',
    'Data Wall 2.0' : 'ice',
    'Fang' : 'ice',
    'Fang 2.0' : 'ice',
    'Fetch 4.0.1' : 'ice',
    'Filter' : 'ice',
    'Fire Wall' : 'ice',
    'Banpei' : 'ice',
    'Bolter Cluster' : 'ice',
    'Cerberus' : 'ice',
    'Corporate Boon' : 2,
    'Corporate Coup' : 2,
    'Corporate Downsizing' : 2,
    'Corporate Retreat' : 3,
    'Corporate War' : 3,
    'Data Fort Reclamation' : 2,
    'Detroit Police Contract' : 1,
    'Employee Empowerment' : 3,
    'Hostile Takeover' : 1,
    'Ice Transmutation' : 3,
    'Main Office Relocation' : 3,
    'Marine Arcology' : 2,
    'Netwatch Operations Office' : 2,
    'On-Call Solo Team' : 3,
    'Political Coup' : 2,
    'Polymer Breakthrough' : 3,
    'Priority Requisition' : 3,
    'Private Cybernet Police' : 2,
    'Project Babylon' : 1,
    'Security Net Optimization' : 3,
    'Subsidiary Branch' : 1,
    'Tycho Extension' : 4,
    'Data Fort Remapping' : 2,
    'Superserum' : 2,
    'Theorem Proof' : 3,
    'Unlisted Research Lab' : 2,
    'AI Board Member' : 3,
    'Charity Takeover' : 1,
    'Corporate Headhunters' : 3,
    'Fetal AI' : 3,
    'Marked Accounts' : 2,
    'Please Don\'t Choke Anyone' : 2,
    'Project Venice' : 2,
    'Project Zurich' : 2,
    'Viral Breeding Ground' : 2,
    'World Domination' : 3,
    'Indiscriminate Response Team' : 'asset',
    'Satellite Monitors' : 'asset',
    'Strategic Planning Group' : 'asset',
    'Bel-Digmo Antibody' : 'asset',
    'Cybertech Think Tank' : 'asset',
    'Department of Misinformation' : 'asset',
    'Doppelganger Antibody' : 'asset',
    'Executive Boot Camp' : 'asset',
    'Government Contract' : 'asset',
    'LDL Traffic Analyzers' : 'asset',
    'Pattel Antibody' : 'asset',
    'Siren' : 'asset',
    'Stereogram Antibody' : 'asset',
    'Syd Meyer Superstores' : 'asset',
    'Blood Cat' : 'asset',
    'City Surveillance' : 'asset',
    'Corporate Negotiating Center' : 'asset',
    'Data Masons' : 'asset',
    'Disinfectant, Inc.' : 'asset',
    'Encoder, Inc.' : 'asset',
    'Fortress Architects' : 'asset',
    'I Got a Rock' : 'asset',
    'Krumz' : 'asset',
    'Nevinyrral' : 'asset',
    'Skalderviken SA Beta Test Site' : 'asset',
    'Schlaghund' : 'asset',
    'Pacifica Regional AI' : 'asset',
    'ACME Savings and Loan' : 'asset',
    'Chicago Branch' : 'asset',
    'Corprunner\'s Shattered Remains' : 'asset',
    'Cowboy Sysop' : 'asset',
    'Department of Truth Enhancement' : 'asset',
    'ESA Contract' : 'asset',
    'Euromarket Consortium' : 'asset',
    'Experimental AI' : 'asset',
    'Hacker Tracker Central' : 'asset',
    'Information Laundering' : 'asset',
    'Investment Firm' : 'asset',
    'Newsgroup Taunting' : 'asset',
    'Omniscience Foundation' : 'asset',
    'Remote Facility' : 'asset',
    'Rescheduler' : 'asset',
    'Rustbelt HQ Branch' : 'asset',
    'Solo Squad' : 'asset',
    'South African Mining Corp' : 'asset',
    'TRAP!' : 'asset',
    'Vacant Soulkiller' : 'asset',
    'Vapor Ops' : 'asset',
    'Virus Test Site' : 'asset',
    'BBS Whispering Campaign' : 'asset',
    'Braindance Campaign' : 'asset',
    'Holovid Campaign' : 'asset',
    'Rockerboy Promotion' : 'asset',
    'Setup!' : 'asset',
    'Spinn Public Relations' : 'asset',
    'London City Grid' : 'upgrade',
    'Self-Destruct' : 'upgrade',
    'Shock Treatment' : 'upgrade',
    'Sterdroid' : 'upgrade',
    'Street Enforcer' : 'upgrade',
    'Herman Revista' : 'upgrade',
    'Lesley Major' : 'upgrade',
    'Lisa Blight' : 'upgrade',
    'Marcel DeSoleil' : 'upgrade',
    'Networked Center' : 'upgrade',
    'Obfuscated Fortress' : 'upgrade',
    'Panic Button' : 'upgrade',
    'Pavit Bharat' : 'upgrade',
    'Rasmin Bridger' : 'upgrade',
    'Raymond Ellison' : 'upgrade',
    'Research Bunker' : 'upgrade',
    'Simon Francisco' : 'upgrade',
    'Weapons Depot' : 'upgrade',
    'Chester Mix' : 'upgrade',
    'Chimera' : 'upgrade',
    'Crybaby' : 'upgrade',
    'Aardvark' : 'upgrade',
    'Dieter Esslin' : 'upgrade',
    'Jenny Jett' : 'upgrade',
    'New Galveston City Grid' : 'upgrade',
    'Jerusalem City Grid' : 'upgrade',
    'Omni Kismet, Ph.D' : 'upgrade',
    'Roving Submarine' : 'upgrade',
    'Singapore City Grid' : 'upgrade',
    'Tesseract Fort Construction' : 'upgrade',
    'Tokyo-Chiba Infighting' : 'upgrade',
    'Twenty-Four-Hour Surveillance' : 'upgrade',
    'Washington, D.C., City Grid' : 'upgrade',
    'Antiquated Interface Routines' : 'upgrade',
    'Bizarre Encryption Scheme' : 'upgrade',
    'Crystal Palace Station Grid' : 'upgrade',
    'Dedicated Response Team' : 'upgrade',
    'Dr. Dreff' : 'upgrade',
    'Namatoki Plaza' : 'upgrade',
    'Olivia Salazar' : 'upgrade',
    'Paris City Grid' : 'upgrade',
    'Red Herrings' : 'upgrade',
    'Rio de Janeiro City Grid' : 'upgrade',
    'Turbeau Delacroix' : 'upgrade',
    'AI Chief Financial Officer' : 2,
    'Artificial Security Directors' : 1,
    'Bioweapons Engineering' : 3,
    'Black Ice Quality Assurance' : 2,
    'Encryption Breakthrough' : 2,
    'Executive Extraction' : 1,
    'Genetics-Visionary Acquisition' : 1,
    'Political Overthrow' : 6,
    'Security Purge' : 2,
    'Strike Force Kali' : 3,
    'Superior Net Barriers' : 3,
}

const corp_cards_array =
      [
	  'Badtimes',
	  'Corporate Shuffle',
	  'Reclamation Project',
	  'London City Grid',
	  'Self-Destruct',
	  'Shock Treatment',
	  'Sterdroid',
	  'Street Enforcer',
	  'Indiscriminate Response Team',
	  'Satellite Monitors',
	  'Strategic Planning Group',
	  'Data Fort Remapping',
	  'Superserum',
	  'Theorem Proof',
	  'Unlisted Research Lab',
	  'Baskerville',
	  'Bolter Swarm',
	  'Brain Drain',
	  'Deadeye',
	  'Dumpster',
	  'Entrapment',
	  'Glacier',
	  'Imperial Guard',
	  'Puzzle',
	  'Trapdoor',
	  'Vortex',
	  'AI Board Member',
	  'Charity Takeover',
	  'Corporate Headhunters',
	  'Fetal AI',
	  'Marked Accounts',
	  'Please Don\'t Choke Anyone',
	  'Project Venice',
	  'Project Zurich',
	  'Viral Breeding Ground',
	  'World Domination',
	  'Brain Wash',
	  'Bug Zapper',
	  'Caryatid',
	  'Chihuahua',
	  'Colonel Failure',
	  'Coyote',
	  'Credit Blocks',
	  'Datacomb',
	  'Death Yo-Yo',
	  'Digiconda',
	  'Dog Pile',
	  'Food Fight',
	  'Galatea',
	  'Gatekeeper',
	  'Homing Missile',
	  'Hunting Pack',
	  'Iceberg',
	  'Lesser Arcana',
	  'Marionette',
	  'Mastermind',
	  'Minotaur',
	  'Misleading Access Menus',
	  'Mobile Barricade',
	  'Riddler',
	  'Roadblock',
	  'Sandstorm',
	  'Scaffolding',
	  'Snowbank',
	  'Sphinx 2006',
	  'Sumo 2008',
	  'Toughonium(tm) Wall',
	  'Tumblers',
	  'Twisty Passages',
	  'Walking Wall',
	  'Washed-Up Solo Construct',
	  'Bel-Digmo Antibody',
	  'Cybertech Think Tank',
	  'Department of Misinformation',
	  'Doppelganger Antibody',
	  'Executive Boot Camp',
	  'Government Contract',
	  'LDL Traffic Analyzers',
	  'Pattel Antibody',
	  'Siren',
	  'Stereogram Antibody',
	  'Syd Meyer Superstores',
	  'Herman Revista',
	  'Lesley Major',
	  'Lisa Blight',
	  'Marcel DeSoleil',
	  'Networked Center',
	  'Obfuscated Fortress',
	  'Panic Button',
	  'Pavit Bharat',
	  'Rasmin Bridger',
	  'Raymond Ellison',
	  'Research Bunker',
	  'Simon Francisco',
	  'Weapons Depot',
	  'Corporate Guard(r) Temps',
	  'Credit Consolidation',
	  'Data Sifters',
	  'Emergency Rig',
	  'Manhunt',
	  'Rent-to-Own Contract',
	  'Schlaghund Pointers',
	  'Underworld Mole',
	  'Chester Mix',
	  'Chimera',
	  'Crybaby',
	  'Aardvark',
	  'Dieter Esslin',
	  'Jenny Jett',
	  'New Galveston City Grid',
	  'Jerusalem City Grid',
	  'Omni Kismet, Ph.D',
	  'Roving Submarine',
	  'Singapore City Grid',
	  'Tesseract Fort Construction',
	  'Tokyo-Chiba Infighting',
	  'Twenty-Four-Hour Surveillance',
	  'Washington, D.C., City Grid',
	  'AI Chief Financial Officer',
	  'Artificial Security Directors',
	  'Bioweapons Engineering',
	  'Black Ice Quality Assurance',
	  'Encryption Breakthrough',
	  'Executive Extraction',
	  'Genetics-Visionary Acquisition',
	  'Political Overthrow',
	  'Security Purge',
	  'Strike Force Kali',
	  'Superior Net Barriers',
	  'Cortical Scanner',
	  'Endless Corridor',
	  'Fatal Attractor',
	  'Wall of Ice',
	  'Tutor',
	  'Vacuum Link',
	  'Laser Wire',
	  'Razor Wire',
	  'Reinforced Wall',
	  'Too Many Doors',
	  'Shotgun Wire',
	  'Nerve Labyrinth',
	  'Haunting Inquisition',
	  'Blood Cat',
	  'City Surveillance',
	  'Corporate Negotiating Center',
	  'Data Masons',
	  'Disinfectant, Inc.',
	  'Encoder, Inc.',
	  'Fortress Architects',
	  'I Got a Rock',
	  'Krumz',
	  'Nevinyrral',
	  'Skalderviken SA Beta Test Site',
	  'Schlaghund',
	  'Pacifica Regional AI',
	  'Falsified Transactions Expert',
	  'New Blood',
	  'Silver Lining Recovery Protocol',
	  'Corporate Boon',
	  'Corporate Coup',
	  'Corporate Downsizing',
	  'Corporate Retreat',
	  'Corporate War',
	  'Data Fort Reclamation',
	  'Detroit Police Contract',
	  'Employee Empowerment',
	  'Hostile Takeover',
	  'Ice Transmutation',
	  'Main Office Relocation',
	  'Marine Arcology',
	  'Netwatch Operations Office',
	  'On-Call Solo Team',
	  'Political Coup',
	  'Polymer Breakthrough',
	  'Priority Requisition',
	  'Private Cybernet Police',
	  'Project Babylon',
	  'Security Net Optimization',
	  'Subsidiary Branch',
	  'Tycho Extension',
	  'Ball and Chain',
	  'Canis Major',
	  'Canis Minor',
	  'Cinderella',
	  'Code Corpse',
	  'Data Darts',
	  'Data Naga',
	  'Data Raven',
	  'Fragmentation Storm',
	  'Hunter',
	  'Jack Attack',
	  'Liche',
	  'Mastiff',
	  'Mazer',
	  'Pocket Virtual Reality',
	  'Rock is Strong',
	  'Sentinels Prime',
	  'Shock.r',
	  'Viral 15',
	  'Virizz',
	  'Antiquated Interface Routines',
	  'Bizarre Encryption Scheme',
	  'Crystal Palace Station Grid',
	  'Dedicated Response Team',
	  'Dr. Dreff',
	  'Namatoki Plaza',
	  'Olivia Salazar',
	  'Paris City Grid',
	  'Red Herrings',
	  'Rio de Janeiro City Grid',
	  'Turbeau Delacroix',
	  'ACME Savings and Loan',
	  'Chicago Branch',
	  'Corprunner\'s Shattered Remains',
	  'Cowboy Sysop',
	  'Department of Truth Enhancement',
	  'ESA Contract',
	  'Euromarket Consortium',
	  'Experimental AI',
	  'Hacker Tracker Central',
	  'Information Laundering',
	  'Investment Firm',
	  'Newsgroup Taunting',
	  'Omniscience Foundation',
	  'Remote Facility',
	  'Rescheduler',
	  'Rustbelt HQ Branch',
	  'Solo Squad',
	  'South African Mining Corp',
	  'TRAP!',
	  'Vacant Soulkiller',
	  'Vapor Ops',
	  'Virus Test Site',
	  'Team Restructuring',
	  'Annual Reviews',
	  'Closed Accounts',
	  'Corporate Detective Agency',
	  'Datapool by Zetatech',
	  'Day Shift',
	  'Edgerunner, Inc., Temps',
	  'Off-Site Backups',
	  'Overtime Incentives',
	  'Power Grid Overload',
	  'Project Consultants',
	  'Punitive Counterstrike',
	  'Scorched Earth',
	  'BBS Whispering Campaign',
	  'Braindance Campaign',
	  'Holovid Campaign',
	  'Rockerboy Promotion',
	  'Setup!',
	  'Spinn Public Relations',
	  'PI in the \'Face',
	  'Asp',
	  'Homewrecker',
	  'Ice Pick Willie',
	  'Keeper',
	  'Neural Blade',
	  'Quandary',
	  'Rex',
	  'Scramble',
	  'Sleeper',
	  'TKO 2.0',
	  'Triggerman',
	  'Wall of Static',
	  'Zombie',
	  'Cortical Scrub',
	  'Crystal Wall',
	  'D\'Arc Knight',
	  'Data Wall',
	  'Data Wall 2.0',
	  'Fang',
	  'Fang 2.0',
	  'Fetch 4.0.1',
	  'Filter',
	  'Fire Wall',
	  'Banpei',
	  'Bolter Cluster',
	  'Cerberus',
	  'Efficiency Experts',
	  'Management Shake-Up',
	  'Netwatch Credit Voucher',
	  'Night Shift',
	  'Planning Consultants',
	  'Systematic Layoffs',
	  'Trojan Horse',
	  'Urban Renewal',
	  'Accounts Receivable',
	  'Audit of Call Records',
	  'Chance Observation'
      ];

const runner_cards_array =
      [
	  'Boostergang Connections',
	  'Corruption',
	  'Do the \'Drine [TM]',
	  'Finders Keepers',
	  'Gypsy [TM] Schedule Analyzer',
	  'Library Search',
	  'Meat Upgrade',
	  'Networking',
	  'Panzer Run',
	  'Running Interference',
	  'Early Worm',
	  'Matador',
	  'MS-todon',
	  'Psychic Friend',
	  'Rent-I-Con',
	  'Schematics Search Engine',
	  'Superglue',
	  'Little Black Box',
	  'Omnitech "Spinal Tap" Cybermodem',
	  'Omnitech Wet Drive',
	  'Vintage Camaro',
	  'Zetatech Portastation',
	  'Crash Space',
	  'Elena Laskova',
	  'Executive File Clerk',
	  'Sandbox Dig',
	  'Armageddon',
	  'Big Frackin\' Gun',
	  'Black Widow',
	  'Boring Bit',
	  'Bulldozer',
	  'Corrosion',
	  'Crumble',
	  'Disintegrator',
	  'Enterprise, Inc., Shields',
	  'Forward\'s Legacy',
	  'Fubar',
	  'Garbage In',
	  'Highlighter',
	  'Lockjaw',
	  'Morphing Tool',
	  'Redecorator',
	  'Scaldan',
	  'Skeleton Passkeys',
	  'Skullcap',
	  'Taxman',
	  'Vienna 22',
	  'Viral Pipeline',
	  'Wrecking Ball',
	  'Cortical Cybermodem',
	  'Cortical Stimulators',
	  'Eurocorpse(tm) Spin Chip',
	  'Lucidrine(tm) Drip Feed',
	  'Sunburst Cranial Interface',
	  'The Deck',
	  'Airport Locker',
	  'Back Door to Netwatch',
	  'Back Door to Rivals',
	  'Bargain with Viacox',
	  'Bolt-Hole',
	  'Chiba Bank Account',
	  'Credit Subversion',
	  'Death from Above',
	  'Expendable Family Member',
	  'Get Ready to Rumble',
	  'HQ Mole',
	  'Liberated Savings Account',
	  'Mercenary Subcontract',
	  'Precision Bribery',
	  'R&D Mole',
	  'Runner Sensei',
	  'Simulacrum',
	  'Streetware Distributor',
	  'Swiss Bank Account',
	  'Time to Collect',
	  'Wired Switchboard',
	  'All-Hands',
	  'Blackmail',
	  'Cruising for Netwatch',
	  'Decoy Signal',
	  'Demolition Run',
	  'Disgruntled Ice Technician',
	  'Drone for a Day',
	  'Faked Hit',
	  'Frame-Up',
	  'Hijack',
	  'Ice and Data Special Report',
	  'Identity Donor',
	  'Live News Feed',
	  'On the Fast Track',
	  'Pirate Broadcast',
	  'Poisoned Water Supply',
	  'Prearranged Drop',
	  'Promises, Promises',
	  'Reconnaissance',
	  'Remote Detonator',
	  'Rush Hour',
	  'Senatorial Field Trip',
	  'Stakeout',
	  'Subliminal Corruption',
	  'Test Spin',
	  'The Personal Touch',
	  'Weefle Initiation',
	  'Access to Arasaka',
	  'Access to Kiribati',
	  'Back Door to Orbital Air',
	  'Fall Guy',
	  'Nomad Allies',
	  'Nasuko Cycle',
	  'Loony Goon',
	  'Piledriver',
	  'Raffles',
	  'Ramming Piston',
	  'Raptor',
	  'Shaka',
	  'Tinweasel',
	  'Wild Card',
	  'Wizard\'s Book',
	  'Worm',
	  'Black Dahlia',
	  'Codecracker',
	  'Codeslinger',
	  'Cyfermaster',
	  'Hammer',
	  'Jackhammer',
	  'Afreet',
	  'Bakdoor',
	  'Blink',
	  'Boardwalk',
	  'Butcher Boy',
	  'Cascade',
	  'Cockroach',
	  'Dogcatcher',
	  'Dropp',
	  'Expert Schedule Analyzer',
	  'Fait Accompli',
	  'Flak',
	  'Gremlins',
	  'Grubb',
	  'I Spy',
	  'Imp',
	  'Krash',
	  'Mouse',
	  'Newsgroup Filter',
	  'Pattel\'s Virus',
	  'Pox',
	  'R&D Protocol File',
	  'Rabbit',
	  'Replicator',
	  'Shredder Uplink Protocol',
	  'Signpost',
	  'Skivviss',
	  'Speed Trap',
	  'Startup Immolator',
	  'Zetatech Software Installer',
	  'Raven Microcyb Owl',
	  'Techtronica Utility Suit',
	  '"Armadillo" Armored Road Home',
	  'Armored Fridge',
	  'Artemis 2020',
	  'Dermatech Bodyplating',
	  '"Drifter" Mobile Environment',
	  'Militech MRAM Chip',
	  'MRAM Chip',
	  'Pandora\'s Deck',
	  'Danshi\'s Second ID',
	  'Databroker',
	  'Floating Runner BBS',
	  'Hell\'s Run',
	  'Junkyard BBS',
	  'Karl de Veres, Corporate Stooge',
	  'Loan from Chiba',
	  'Restrictive Net Zoning',
	  'Smith\'s Pawnshop',
	  'Submarine Uplink',
	  'Technician Lover',
	  'Trauma Team',
	  'Umbrella Policy',
	  'Wilson, Weeflerunner Apprentice',
	  'Bodyweight Synthetic Blood',
	  'Core Command: Jettison Ice',
	  'Inside Job',
	  'Kilroy Was Here',
	  'Lucidrine Booster Drug',
	  'Private LDL Access',
	  'Romp through HQ',
	  'Security Code WORM Chip',
	  'Social Engineering',
	  'Valu-Pak Software Bundle',
	  'Weather-to-Finance Pipe',
	  'Ice and Data\'s Guide to the Net',
	  'All-Nighter',
	  'Custodial Position',
	  'Edited Shipping Manifests',
	  'Executive Wiretaps',
	  'Forgotten Backup Chip',
	  'Gideon\'s Pawn Shop',
	  'Hunt Club BBS',
	  'If You Want It Done Right...',
	  'Jack \'n\' Joe',
	  'Livewire\'s Contacts',
	  'Mantis, Fixer-at-Large',
	  'Open-Ended Mileage Program',
	  'Score!',
	  'Temple Microcode Outlet',
	  'Back Door to Hilliard',
	  'Broker',
	  'Crash Everett, Inventive Fixer',
	  'Leland, Corporate Bodyguard',
	  'Rigged Investments',
	  'The Short Circuit',
	  'Short-Term Contract',
	  'The Springboard',
	  'Parraline 5750',
	  'PK-6089a',
	  'R&D Interface',
	  'Raven Microcyb Eagle',
	  'Tycho Mem Chip',
	  'WuTech Mem Chip',
	  'Zetatech Mem Chip',
	  'ZZ22 Speed Chip',
	  'Corolla Speed Chip',
	  '"Green Knight" Surge Buffers',
	  'HQ Interface',
	  'Microtech Backup Drive',
	  'Baedeker\'s Net Map',
	  'Cloak',
	  'Invisibility',
	  'SeeYa',
	  'Shield',
	  'Smarteye',
	  'Vewy Vewy Quiet',
	  'Force Shield',
	  'Dwarf',
	  'Clown',
	  'Record Reconstructor',
	  'Lifesaver Nanosurgeons',
	  'Microtech \'Trode Set',
	  'Full Body Conversion',
	  'Bodyweight(tm) Data Creche',
	  'Arasaka Portable Prototype',
	  'Access Through Alpha',
	  'Aujourd\'Oui',
	  'Code Viral Cache',
	  'Corporate Ally',
	  'Diplomatic Immunity',
	  'N.E.T.O.',
	  'Preying Mantis',
	  'Ronin Around',
	  'The Shell Traders',
	  'Silicon Saloon Franchise',
	  'Top Runners Conference',
	  'Quest for Cattekin',
	  'Field Reporter for Ice and Data',
	  'Microtech AI Interface',
	  'Mystery Box',
	  'Netspace Inverter',
	  'Reflector',
	  'Scatter Shot',
	  'Self-Modifying Code',
	  'Snowball',
	  'Succubus',
	  'AI Boon',
	  'Bartmoss Memorial Icebreaker',
	  'Dupre',
	  'Emergency Self-Construct',
	  'Evil Twin',
	  'False Echo',
	  'Incubator',
	  'Japanese Water Torture',
	  'Joan of Arc',
	  'Poltergeist',
	  'Deep Thought',
	  'Anonymous Tip',
	  'Arasaka Owns You',
	  'Deal with Militech',
	  'Desperate Competitor',
	  'Forged Activation Orders',
	  'Fortress Respecification',
	  'misc.for-sale',
	  'MIT West Tier',
	  'Organ Donor',
	  'Playful AI',
	  'Sneak Preview',
	  'Stumble through Wilderspace',
	  'Synchronized Attack on HQ',
	  'Terrorist Reprisal',
	  'Total Genetic Retrofit',
	  'Priority Wreck',
	  'Hot Tip for WNS',
      ]

function corp_card_type(name) {
    let card_type = corp_cards[name];
    if(card_type == null)
	return 'operation';
    if(Number.isInteger(card_type))
	return 'agenda';
    return card_type;
}

function runner_card_type(name) {
    let card_type = runner_cards[name];
    if(card_type == undefined)
	console.log(name);
    return card_type;
}

function to_image_name(name) {
    let res = name.toLowerCase().replaceAll("(tm)", " tm").replaceAll("(r)", " r").replaceAll(" ", "-").replaceAll("'", "-").replaceAll('"', "").replaceAll(":", "");

    return ("resources/card-images/" + res + ".jpg");
}

function count_deck(map) {
    let count = 0;
    for (let [key, value] of map) {
	count += value;
    }

    return count;
}

function is_agenda(name) {
    return corp_card_type(name) == 'agenda';
}

function count_ap(map) {
    let count = 0;
    for (let [key, value] of map) {
	count += corp_cards[key]*value;
    }

    return count;
}

function ap_limit(numcards) {
    if(numcards <= 45)
	return "18-19";
    else {
	let qty = numcards - 44;
	let adj = 0;
	while(qty > 0) {
	    qty = qty - 5;
	    adj += 2;
	}

	let lownum = 18+adj;
	let highnum = 19 + adj;
	//return "18-19";
	return `${lownum}-${highnum}`
    }
}

var is_corp_card = function(name) {
    return corp_cards_array.includes(name);
}

/* these probably shouldn't be here
   but what you finna do */
function addcard() {
    let selector = document.getElementById("select-cards-id");
    let table = document.getElementById("extra-cards-table");
    let tr = document.createElement("tr");
    let td = document.createElement("td");
    let tdspan = document.createElement("span");
    let selected = selector.value;
    let removebutton = document.createElement("button");
    removebutton.innerHTML = "remove";
    removebutton.addEventListener("click", function() {table.removeChild(tr)});
    let tdbutton = document.createElement("td");
    tdbutton.appendChild(removebutton);
    tdspan.innerHTML = selected;
    tdspan.value = selected;
    tdspan.classList.add("extra-card");
    td.appendChild(tdspan);
    tr.appendChild(td);
    tr.appendChild(tdbutton);

    // add remove button
    table.appendChild(tr);
}

function populateCards() {
    let element = document.getElementById("select-cards-id");
    let allcards = [].concat(corp_cards_array).concat(runner_cards_array);
    allcards.sort();
    for(var card of allcards) {
	let option = document.createElement("option");
	option.value=card;
	option.innerHTML=card;
	element.appendChild(option);
    }
}
